### ISSUE TITLE
Bug: When user page is deleted but user meta that user has a page is not.

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-user-pages#9]
This issue occurs under the following scenario:

1. User pages plugin is deactivated and/or unistalled 
2. User deletes the pages previously created for users.
3. User re-installs User Pages and activates plugin.
4. In the plugin admin user selects memberships levels that should have user pagesd and selects checkbox to create user pages for existing members.
5. Creation of user pages fails.

The cause of this issue is that the function checks whether the usermeta meta_key for pmproup_user_page exist but not whether the meta_value correlates with an existing post_id.

**Comment by ipokkel** [comment]
Possible workarounds to consider.

- Add option on add on admin page to delete existing pages when plugin is uninstalled, removing entry in usermeta table and related entries in posts and postmeta tables.
- Use [delete_post](https://developer.wordpress.org/reference/hooks/deleted_post/) hook to delete the user meta when the post is deleted
- During page creation check add if true for usermeta table has meta_key pmproup_user_page,  check if posts table has post_id that equals meta_value of pmproup_user_page meta_value

**Comment by ideadude** [comment]
> Use delete_post hook to delete the user meta when the post is deleted

We could/should do this. We set the author of the post to the user's id. So assuming the site admins didn't change the author we could:

1. hook into post delete
2. then get the user id of the author
3. then check for the pmproup_user_page user meta for that user
4. and delete the user meta field IF the id in that meta matches the post id being deleted

**Comment by dparker1005** [comment]
> > Use delete_post hook to delete the user meta when the post is deleted
> 
> We could/should do this. We set the author of the post to the user's id. So assuming the site admins didn't change the author we could:
> 
> 1. hook into post delete
> 2. then get the user id of the author
> 3. then check for the pmproup_user_page user meta for that user
> 4. and delete the user meta field IF the id in that meta matches the post id being deleted

This fix makes sense, but requires running code when the post is deleted, but the original example was specifically about when a post is deleted while PMPro User Pages is deactivated/uninstalled.

In order to account for pages being deleted while this plugin is not active (and thus when any fix we perform on post deletion wouldn't be run), I'd recommend a refactor where we:
1. Create a function to get a user's user page instead of directly querying user meta every time. Change all direct queries to use that function instead
2. In that function, check if the page exists. If the had a page in usermeta but that page no longer exists, delete it

Eventually, we can further update that function to create a new page in the old page's place, though we would need to think about exactly how we want this to work.

@ideadude Thoughts before I start on that function?

**Comment by ideadude** [comment]
> but requires running code when the post is deleted whereas the original example was specifically about when a post is deleted while PMPro User Pages is deactivated/uninstalled.

Oops. I missed that.

> 1. Create a function to get a user's user page instead of directly querying user meta every time. Change all direct queries to use that function instead
> 2. In that function, check if the page exists. If the had a page in usermeta but that page no longer exists, delete it

Sounds great!
